admin=c3VwZXJtYW46U2VjcmV0MDA3
receptionist=c3VwZXJtYW46U2VjcmV0MDA3
doctor=b3RoZXIuZG9jdG9yOlNlY3JldDAwNw==
nurse=T3RoZXIubnVyc2U6U2VjcmV0MDA3
nurseManager=c2ltcmV0LmJla2VsZTpTZWNyZXQwMDc=

receptionist_roles=FrontDesk
doctor_roles=Doctor